apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-service-monitor
  labels:
    project: python
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: python
  namespaceSelector:
    any: true
  endpoints:
  - port: api
    interval: 30s
    path: /metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: ["*"]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: python-alert
spec:
  groups:
  - name: python-alerts
    rules:
    - alert: HighRequestRate  
      expr: rate(info_requests_total[1m]) * 60 > 5  
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Wysoki wskaźnik żądań"
        description: "Metryka info_requests_created generuje więcej niż 5 żądań na minutę."