apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - demo.164.90.222.130.nip.io
    secretName: example-tls
  rules:
  - host: demo.164.90.222.130.nip.io
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 5002
