apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
  labels:
    name: host-path-pod
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: workshop-worker
  volumes:
  - name: host-path
    hostPath:
      path: /files
# In Windows use this path (after modifying) `/run/desktop/mnt/host/c/path/to/file`
  containers:
  - name: host-path-pod-bb
    image: busybox
    command: ['sh', '-c', 'echo running! && sleep 3600']
    volumeMounts:
    - name: host-path
      mountPath: /pod-empty/
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
