apiVersion: v1
kind: Pod
metadata:
  name: myapp-limitrange
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: 128Mi
        cpu: 2
    ports:
      - containerPort: 80
