apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
  persistentVolumeReclaimPolicy: Recycle

