dns: 127.0.0.1.nip.io

redis:
  name: redis
  image: redis:5.0.10
  port: 6379
  pullPolicy: Always
  disk: 1Gi

python:
  name: python-api
  image: marcinmakowski/python-api:redis
  port: 5002

replicaCount: 1
storageClassName: default
