apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    szkolenie: k8s
spec:
  selector:
    app: python
    szkolenie: k8s
  ports:
  - port: 80
    targetPort: api
  type: NodePort
